name: Deploy to Google Cloud

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

      

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Set Python version if needed

      - name: Install Docker dependencies
        run: |
          sudo apt-get remove -y containerd containerd.io
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common

      - name: Install Docker
        run: |
          sudo apt-get remove -y docker docker-engine docker.io containerd runc
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - name: Build Docker image
        run: |
          docker build -t trip-time-prediction .

      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 trip-time-prediction
          
      - name: Authenticate Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.DE_WEEK_7 }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: 'de-week-7'
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.DE_WEEK_7 }}

      - name: Decode and set up credentials
        run: |
          echo "${{ secrets.DE_WEEK_7 }}" | base64 --decode > gcloud-key.json
          gcloud auth activate-service-account --key-file=gcloud-key.json

      - name: Deploy to Google Cloud App Engine
        run: |
          gcloud config set project de-week-7
          gcloud app deploy --quiet
